version: "3"
services:
  test_db:
    image: postgres:latest
    container_name: mydb
    ports:
    - 5432
    volumes:
    - ./pg_db_data:/var/lib/postgresql/data
    environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
     POSTGRES_DB: postgres

  python_loader:
    image: python_loader:latests
    container_name: myloader
    build:
      context: ./
    link:
      - test_db