version: "3"
services:
  test_db:
    image: northwind_postgres:latest
    container_name: mydb
    ports:
    - 5432:5432
    volumes:
    - ./pg_db_data:/var/lib/postgresql/data
    environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
     POSTGRES_DB: postgres